# Generated by Django 5.1.5 on 2025-02-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="max_altitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="max_neg_grade",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="max_pos_grade",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="num_laps",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_cadence",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_heart_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_power",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_running_cadence",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_step_length",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="avg_temperature",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="file",
            field=models.FileField(null=True, upload_to="fit"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="manufacturer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_cadence",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_heart_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_power",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_running_cadence",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_temperature",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="min_heart_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="product_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="sport",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="sub_sport",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_ascent",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_calories",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_descent",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_distance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_elapsed_time",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="total_moving_time",
            field=models.FloatField(null=True),
        ),
    ]
